### ISSUE TITLE
See output?

### ISSUE THREAD

**Issue by jbrooksuk** [statianzo/dokku-supervisord#21]
When using this plugin my app no longer outputs to the `docker logs $APP_NAME` result. Is there a way I can look at it?

**Comment by stepri** [comment]
Same here

**Comment by kenips** [comment]
@statianzo this happens after upgrading to buildpack after https://github.com/progrium/buildstep/pull/109/files. Specifically `/exec` is now symlinked to `/start` which causes the issue. I've just asked if the symlink was intentional, but for now restoring `/exec` to pre 109 fixes the issue.

**Comment by statianzo** [comment]
@kenips Thanks for associating the problem to the symlink change.

**Comment by kenips** [comment]
Hey everyone please give this a test? https://github.com/kenips/dokku-supervisord/tree/bug/wrong_exec

**Comment by kenips** [comment]
Fixed by #26
