### ISSUE TITLE
formatting log

### ISSUE THREAD

**Issue by peerbolte** [statianzo/dokku-supervisord#28]
Is it possible to format the debug log? I would like to remove the headers and empty line such as 
``2015-08-06 10:32:02,512 DEBG 'web' stdout output:``

![screen shot 2015-08-06 at 12 34 35](https://cloud.githubusercontent.com/assets/6849898/9109658/963f3360-3c37-11e5-8a81-ab512513af70.png)

**Comment by statianzo** [comment]
Doesn't look like supervisor allows formatting logs yet, https://github.com/Supervisor/supervisor/issues/553
