### ISSUE TITLE
Application not restarting 

### ISSUE THREAD

**Issue by chrisjhoughton** [statianzo/dokku-supervisord#29]
Hi there! I haven't used supervisord before but really interested to add this plugin to ensure our apps recover as quickly as possible. 

To test things out, I've installed on a dev server and created a sample app https://github.com/chrisjhoughton/supervisor. My goal was to see how the restarting functionality works.

Key thing to note - I'm deliberately crashing the server in `app.js` by running `JSON.parse('chris')`. The server crashes alright, but I can't see anything recovering?

Apologies if this is a noob question.

**Comment by statianzo** [comment]
Can you share the logs of the sample application deploying and running?

**Comment by chrisjhoughton** [comment]
Not quite sure what happened here - I just tried destroying the app and redeploying. Thanks anyway.
